// Generated by Selenium IDE

import baseClass.Utils;
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.FluentWait;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.math.BigDecimal;
import java.util.*;
import java.util.concurrent.TimeUnit;

public class test {
    private WebDriver driver;
    Utils utils = new Utils();
    public JavascriptExecutor jse = (JavascriptExecutor) driver;


    public void setWebDriverFluentWait(int poolInterval, int timeOutDuration, By by) {
        FluentWait<WebDriver> wait = new FluentWait<WebDriver>(driver)
                .withTimeout(timeOutDuration, TimeUnit.SECONDS)
                .pollingEvery(poolInterval, TimeUnit.SECONDS)
                .ignoring(NoSuchElementException.class);
        wait.until(ExpectedConditions.refreshed(ExpectedConditions.visibilityOfElementLocated(by)));

    }

    public void click(WebElement element, WebDriver driver) {

        jse.executeScript("arguments[0].click();", element);
    }

    @Test
    public void Login() throws InterruptedException {
        click(driver.findElement(By.xpath("//*[@id='navbarDropdown']")), driver);
        setWebDriverFluentWait(1, 20, By.xpath("//*[@id='navbarSupportedContent']//li[1]/a"));
        click(driver.findElement(By.xpath("//*[@id='navbarSupportedContent']//li[1]/a")), driver);

    }
}
